apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: monitoring
spec:
  storageClassName: sc-nas-svm1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
